name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
    - name: The PHP Security Checker
      # You may pin to the exact commit or the version.
      # uses: symfonycorp/security-checker-action@bb5092fdb50d4b92d301885fb6d0b0a41cea7bcd
      uses: symfonycorp/security-checker-action@v4
      with:
        # The path to composer.lock is stored (root directory by default)
        lock: ./composer.lock
        # The output format (ansi by default, supported: ansi, junit, markdown, json, or yaml)
        format: ansi
        # Whether to continue when issues are detected (false by default)
        disable-exit-code: 0
